.PHONY: scheduler.gif
scheduler.gif:
	convert -delay 100 scheduler.*.png scheduler.gif

.PHONY: stack.gif
stack.gif:
	convert -delay 200 stack*.png stack.gif

.PHONY: heap-gc.gif
heap-gc.gif:
	convert -delay 200 heap-gc.*.png heap-gc.gif
